import java.util.ArrayList;
import java.util.List;

// Data model representing a deduplicated, ML-scored incident
class DisasterIncident {
    String messageId;
    String rawText;
    double urgencyScore; // Generated by ML model (0.0 to 1.0)
    List<String> detectedKeywords;
    public Object id;
    public Object keywords;

    public DisasterIncident(String messageId, String rawText, double urgencyScore, List<String> detectedKeywords) {
        this.messageId = messageId;
        this.rawText = rawText;
        this.urgencyScore = urgencyScore;
        this.detectedKeywords = detectedKeywords;
    }

    @Override
    public String toString() {
        return String.format("[%s] Urgency: %.4f | Keywords: %s | Text: \"%s\"",
                messageId, urgencyScore, detectedKeywords, rawText);
    }
}

public class MaxHeap {
    private final List<DisasterIncident> heap;

    public MaxHeap() {
        this.heap = new ArrayList<>();
    }

    public boolean isEmpty() {
        return heap.isEmpty();
    }

    public int size() {
        return heap.size();
    }

    /**
     * Inserts a new incident into the Max-Heap in O(log N) time.
     */
    public void insert(DisasterIncident incident) {
        heap.add(incident);
        heapifyUp(heap.size() - 1);
    }

    /**
     * Extracts and returns the highest priority incident in O(log N) time.
     */
    public DisasterIncident extractMax() {
        if (heap.isEmpty()) {
            throw new IllegalStateException("Priority Queue is empty!");
        }

        DisasterIncident maxIncident = heap.get(0);
        DisasterIncident lastIncident = heap.remove(heap.size() - 1);

        if (!heap.isEmpty()) {
            heap.set(0, lastIncident);
            heapifyDown(0);
        }

        return maxIncident;
    }

    /**
     * Restores heap property upwards after insertion.
     */
    private void heapifyUp(int index) {
        while (index > 0) {
            int parentIndex = (index - 1) / 2;
            if (heap.get(index).urgencyScore > heap.get(parentIndex).urgencyScore) {
                swap(index, parentIndex);
                index = parentIndex;
            } else {
                break;
            }
        }
    }

    /**
     * Restores heap property downwards after extraction.
     */
    private void heapifyDown(int index) {
        int maxIndex = index;
        int leftChild = 2 * index + 1;
        int rightChild = 2 * index + 2;

        if (leftChild < heap.size() && heap.get(leftChild).urgencyScore > heap.get(maxIndex).urgencyScore) {
            maxIndex = leftChild;
        }

        if (rightChild < heap.size() && heap.get(rightChild).urgencyScore > heap.get(maxIndex).urgencyScore) {
            maxIndex = rightChild;
        }

        if (index != maxIndex) {
            swap(index, maxIndex);
            heapifyDown(maxIndex);
        }
    }

    private void swap(int i, int j) {
        DisasterIncident temp = heap.get(i);
        heap.set(i, heap.get(j));
        heap.set(j, temp);
    }
}